### ISSUE TITLE
tracking objects fly far away after move from side to side 

### ISSUE THREAD

**Issue by kismeter** [openxrlab/xrslam#11]
when slam started and place a model, the tracking seems good. Then try move phone from side to side several times, the object becoming smaller and smaller until disappear.

**Comment by wangnancpp** [comment]
Current version of XRSLAM has only the ability of odometry. So it can't recover tracking by relocalization.
And we will soon add module of mapping to support reloclization and increase the robustness of tracking.

**Comment by wangni-bupt** [comment]
My test found that this is also the case. It should belong to zero speed drift. Do I need to use ZUPT to directly switch to pure IO to correct it
