### ISSUE TITLE
Initializing failed when porting to Android 

### ISSUE THREAD

**Issue by kismeter** [openxrlab/xrslam#19]
hi,
Trying to porting this project to android device, met initializing always failed, is there any special configuration should be done? Any potential reasons will cause initializing fail?
Thanks

**Comment by huanggan52** [comment]
You can try the availability of offline data, start by recording data using the device and then adjust the noise of the camera and IMU. Next, try changing some parameters in the xrslam-pc reader. This will help you determine whether the offline data is working properly.

**Comment by kismeter** [comment]
I use MH01 datasets, can’t get the same results as PC or iOS
