### ISSUE TITLE
Windows, runtime error

### ISSUE THREAD

**Issue by antithing** [openxrlab/xrslam#2]
Hi! This code looks great, thank you for making it available. 

I have it built and compiled on Windows, but when i try to run the euroc dataset, i see:

`Microsoft Windows [Version 10.0.22000.856]
(c) Microsoft Corporation. All rights reserved.

D:\testing\xrprimer-main\xrslam-main\build\xrslam-pc\player\Release>xrslam-pc-player -c configs/euroc.yaml --tum trajectory.tum euroc:///D:/datasets/MH_05_difficult
2022-09-02 16:33:44.656 - [XRSLAM][info]
ΓûêΓûêΓòù  ΓûêΓûêΓòùΓûêΓûêΓûêΓûêΓûêΓûêΓòù ΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓòùΓûêΓûêΓòù      ΓûêΓûêΓûêΓûêΓûêΓòù ΓûêΓûêΓûêΓòù   ΓûêΓûêΓûêΓòù
ΓòÜΓûêΓûêΓòùΓûêΓûêΓòöΓò¥ΓûêΓûêΓòöΓòÉΓòÉΓûêΓûêΓòùΓûêΓûêΓòöΓòÉΓòÉΓòÉΓòÉΓò¥ΓûêΓûêΓòæ     ΓûêΓûêΓòöΓòÉΓòÉΓûêΓûêΓòùΓûêΓûêΓûêΓûêΓòù ΓûêΓûêΓûêΓûêΓòæ
 ΓòÜΓûêΓûêΓûêΓòöΓò¥ ΓûêΓûêΓûêΓûêΓûêΓûêΓòöΓò¥ΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓòùΓûêΓûêΓòæ     ΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓòæΓûêΓûêΓòöΓûêΓûêΓûêΓûêΓòöΓûêΓûêΓòæ
 ΓûêΓûêΓòöΓûêΓûêΓòù ΓûêΓûêΓòöΓòÉΓòÉΓûêΓûêΓòùΓòÜΓòÉΓòÉΓòÉΓòÉΓûêΓûêΓòæΓûêΓûêΓòæ     ΓûêΓûêΓòöΓòÉΓòÉΓûêΓûêΓòæΓûêΓûêΓòæΓòÜΓûêΓûêΓòöΓò¥ΓûêΓûêΓòæ
ΓûêΓûêΓòöΓò¥ ΓûêΓûêΓòùΓûêΓûêΓòæ  ΓûêΓûêΓòæΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓòæΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓòùΓûêΓûêΓòæ  ΓûêΓûêΓòæΓûêΓûêΓòæ ΓòÜΓòÉΓò¥ ΓûêΓûêΓòæ
ΓòÜΓòÉΓò¥  ΓòÜΓòÉΓò¥ΓòÜΓòÉΓò¥  ΓòÜΓòÉΓò¥ΓòÜΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓò¥ΓòÜΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓò¥ΓòÜΓòÉΓò¥  ΓòÜΓòÉΓò¥ΓòÜΓòÉΓò¥     ΓòÜΓòÉΓò¥
2022-09-02 16:33:44.656 - [XRSLAM][info] Configurations:
Config::camera_intrinsic:
4.58654e+02 0.00000e+00 3.67215e+02
0.00000e+00 4.57296e+02 2.48375e+02
0.00000e+00 0.00000e+00 1.00000e+00

Config::camera_to_body_rotation:
-7.70718e-03  1.04993e-02  7.01753e-01  7.12301e-01

Config::camera_to_body_translation:
-2.16401e-02 -6.46770e-02  9.81073e-03

Config::imu_to_body_rotation:
0.00000e+00 0.00000e+00 0.00000e+00 1.00000e+00

Config::imu_to_body_translation:
0.00000e+00 0.00000e+00 0.00000e+00

Config::keypoint_noise_cov:
5.00000e-01 0.00000e+00
0.00000e+00 5.00000e-01

Config::gyroscope_noise_cov:
2.87913e-08 0.00000e+00 0.00000e+00
0.00000e+00 2.87913e-08 0.00000e+00
0.00000e+00 0.00000e+00 2.87913e-08

Config::accelerometer_noise_cov:
4.00000e-06 0.00000e+00 0.00000e+00
0.00000e+00 4.00000e-06 0.00000e+00
0.00000e+00 0.00000e+00 4.00000e-06

Config::gyroscope_bias_noise_cov:
3.76088e-10 0.00000e+00 0.00000e+00
0.00000e+00 3.76088e-10 0.00000e+00
0.00000e+00 0.00000e+00 3.76088e-10

Config::accelerometer_bias_noise_cov:
9.00000e-06 0.00000e+00 0.00000e+00
0.00000e+00 9.00000e-06 0.00000e+00
0.00000e+00 0.00000e+00 9.00000e-06

Config::sliding_window_size: 10
Config::sliding_window_force_keyframe_landmarks: 35
Config::sliding_window_tracker_frequent: 1
Config::feature_tracker_min_keypoint_distance: 1.00000e+01
Config::feature_tracker_max_keypoint_detection: 1000
Config::feature_tracker_max_init_frames: 60
Config::feature_tracker_max_frames: 20
Config::feature_tracker_predict_keypoints: true
Config::initializer_keyframe_gap: 5
Config::initializer_min_matches: 50
Config::initializer_min_parallax: 1.00000e+01
Config::initializer_min_triangulation: 20
Config::initializer_min_landmarks: 30
Config::initializer_refine_imu: true
Config::visual_localization_enable: false
Config::visual_localization_config_ip: 0.0.0.0
Config::visual_localization_config_port: 0
Config::solver_iteration_limit: 30
Config::solver_time_limit: 1.00000e+06

THREADING DISABLE

GLFW Error: WGL: Failed to make context current: The handle is invalid.
GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported.
GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported.
GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported.
`

And an empty UI:

![image](https://user-images.githubusercontent.com/11506730/188246470-151b7845-e9b1-42f0-9718-6ed58c84d322.png)

I press the 'Stopped' button, but nothing happens.
What am i missing?
Thanks!

**Comment by panxkun** [comment]
it seems that the SLAM pc-player can be built successfully on windows and start up , but the data stream was blocked. Take a try this command

D:\testing\xrprimer-main\xrslam-main\build\xrslam-pc\player\Release>xrslam-pc-player -c configs/euroc.yaml --tum trajectory.tum euroc:///D:/datasets/MH_05_difficult/**mav0**

dataset path need set to the `mav0` folder

**Comment by antithing** [comment]
Hi, thank you for getting back to me. I used the command as you suggest, but i see the same result. The button has no effect, and the slam does not run. Thank you again

**Comment by panxkun** [comment]
Sorry for the unfamiliar with the command line mode on Windows. It is better to use absolute paths for reading files, including the configuration files `euroc.yaml`

**Comment by antithing** [comment]
I have adjusted the command to be:
`
xrslam-pc-player -c D:/testing/xrprimer-main/xrslam-main/build/xrslam-pc/player/Release/configs/euroc.yaml --tum trajectory.tum euroc:///D:/datasets/MH_05_difficult/mav0`

But I see the same issue! I might try hardcoding the filepaths in the c++

**Comment by antithing** [comment]
Hi again,

Stepping through the code, it appears that this function:

`    void load(const std::string &filename) {
        items.clear();
        if (FILE *csv = fopen(filename.c_str(), "r")) {
            char header_line[2048];
            fscanf(csv, "%2047[^\r]\r\n", header_line);
            char filename_buffer[2048];
            CameraData item;
            while (!feof(csv)) {
                memset(filename_buffer, 0, 2048);
                if (fscanf(csv, "%lf,%2047[^\r]\r\n", &item.t,
                           filename_buffer) != 2) {
                    break;
                }
                item.t *= 1e-9;
                item.filename = std::string(filename_buffer);
                items.emplace_back(std::move(item));
            }
            fclose(csv);
        }
    }

`

Does not work on Windows. Even with a hardcoded file path, it still returns empty.

Thanks!

**Comment by huanggan52** [comment]
Perhaps it is because the symbol at the end of each line of text is expressed differently in linux and windows, you can replace "[^\r]" with "[^\n]" to have a try，and three symbols need to be modified in the above file .

**Comment by antithing** [comment]
Thank you! That has it running. however, i now get a crash here:

`xrslam->track_accelerometer(t, a.x(), a.y(), a.z());`

`Unhandled exception at 0x00007FFEDC12474C in xrslam-pc-player.exe: Microsoft C++ exception: cv::Exception at memory location 0x00000055E5B5DC80.`

**Comment by itsuhane** [comment]
`cv::Exception` suggests something wrong with OpenCV. OpenCV is only used for image loading/keypoint tracking. Can you confirm that the images are correctly loaded?

**Comment by antithing** [comment]
Hi, I have now hardcoded the paths, and can confirm that the image paths are correct (i am showing the images using imshow) My reader looks like this:

![image](https://user-images.githubusercontent.com/11506730/189191401-29cf4e73-1ae6-4fbb-b5a4-1fe1ee052621.png)

So it appears the data is loaded correctly, however I still see the crash. 

If i comment out this line:

`xrslam->track_accelerometer(t, a.x(), a.y(), a.z());`

the application runs, and i see the images update, but the 3d view stays empty.

Thanks!

**Comment by itsuhane** [comment]
The VIO will not initialize itself if there are no IMU measurements, hence outputs zero poses.

Did you still get `cv::Exception` for the crash? If so, I recommend you check opencv related code in [`xrslam-extra/src/xrslam/extra/opencv_image.cpp`](https://github.com/openxrlab/xrslam/blob/6590f3fe3a923c3339c2d33ed50ace7cf9409bd3/xrslam-extra/src/xrslam/extra/opencv_image.cpp).

**Comment by antithing** [comment]
Hi, Ah, indeed, the crash is here:

`clahe()->apply(image, image);`

If i comment that line, it crashes on the next :

`buildOpticalFlowPyramid(image, image_pyramid, Size(21, 21),
                            (int)level_num(), true);`

It seems like the image is not loading, but I can view it, and print the type and channels. Very strange! Can you think of anything else i can look at here?

**Comment by itsuhane** [comment]
Back to the dataset reader for euroc, it reads a list file, extracting timestamp and file name from the line.

Maybe you can take a close look at the extracted file name string, see if especially any invisible characters (CRLF) in the path string.

Best,
Jinyu

**Comment by antithing** [comment]
Hi again, if i edit the following to show the image:

`void OpenCvImage::preprocess() {

    cv::imshow("test", image);
    cv::waitKey(1);

    clahe()->apply(image, image);
    image_pyramid.clear();

    buildOpticalFlowPyramid(image, image_pyramid, Size(21, 21),
                            (int)level_num(), true);
}`

It displays the image correctly, but crashes on the ` clahe()->apply(image, image);` line. Strange!

So the images are being loaded, but the function crashes

**Comment by itsuhane** [comment]
I have no experience with windows systems so I need your help for some baseline test.

Can you modify the `main` function in file `xrslam-pc/player/src/main.cpp` to something like this?

```cpp
// starting at line 251:
int main(int argc, char *argv[]) {
    // add the following:
    using namespace cv;
    Mat image = imread(/* an image path known to load */, IMREAD_GRAYSCALE);
    Ptr<CLAHE> clahe = createCLAHE(6.0, cv::Size(8, 8));
    clahe->apply(image, image);
    // ...
```

What it does is simply reading an image and running the CLAHE algorithm (before any real XRSLAM thing kicks in).
If that makes xrslam-pc crash, then there should be something wrong with your local OpenCV build.

Meanwhile, I'll ask the team to see if they can provide a precompiled windows binary for XRPrimer, a tested OpenCV should come with it. So far I haven't managed to build XRPrimer on windows, which is blocking me from further investigating this issue.

Best,
Jinyu

**Comment by antithing** [comment]
Hi, ah apologies! I indeed had an opencv issue! I was linking a opencv 460 lib instead of the included _ext version. 

It is now running as expected on euroc.

next step, to link a live D455  as input! 

Quick question, where can i see the frame time? Are there any fps counters in the code? I am looking for 50 fps, is this an achievable goal?

Thanks again

**Comment by itsuhane** [comment]
That's great.

The D455 sensor comes with RGB-D and IMU data. Currently, XRSLAM only handles (monocular) RGB+IMU, and should support D455 given a correct calibration. You can have a look at the calibration file (`configs/euroc.yaml` for example) to know the required calibration data. In the future, we may support tracking using RGB-D data in XRSLAM.

The time spike is indeed from processing the keyframes (BA of the sliding window). Currently we don't have a frame-rate goal, and the solving process is not optimized. For example, we fully build the whole optimization problem each time, which is definitely not optimal. We will improve the design in the future, meanwhile users can customize the code to fit their need. In your case, you need to optimize the solving, and maybe change the strategy used in the sliding window.

Since the runtime error is resolved, I'll close this issue.
