### ISSUE TITLE
FindTBB error

### ISSUE THREAD

**Issue by ZibYang** [openxrlab/xrslam#30]
according to https://github.com/ceres-solver/ceres-solver/issues/669
when building XRPrimer in Unbuntu 22.04, I got an error:
```
CMake Error at cmake/FindTBB.cmake:434 (file):
  file STRINGS file "/usr/local/include/tbb/tbb_stddef.h" cannot be read.
Call Stack (most recent call first):
```
Before XRPrimer gets an update, you need to:
1. build xrprimer first to get the same error (in order to download some dependences)
2. comment Line 40 in `cmake/external/ceres.cmake`
3. change Line 435 in `_ext/ceres-solver/cmake/FindTBB.cmake` to `"${TBB_INCLUDE_DIR}/oneapi/tbb/version.h"`

**Comment by OctaAIVision** [comment]
i made soft link and solved my problem but u need sudo.
```bash
sudo ln -s /usr/include/tbb/version.h /usr/include/tbb/tbb_stddef.h
```
