### ISSUE TITLE
Custom Dataset

### ISSUE THREAD

**Issue by OctaAIVision** [openxrlab/xrslam#48]
Hi, Thanks for your great job.
I have and OAKD which has IMU + Camera integrated. is there any trick i should do to be able to use my data?
cuz I get in the following loop all the time.
```
        case DatasetReader::AGAIN:{
            continue;
            }
```
would u mind guiding me? do I have to get Synced data? may I  use unsynced data??

**Comment by panxkun** [comment]
The code currently does not perform online correction of sensor timestamps for asynchronous data, so it cannot directly handle asynchronous data at this time. To use online data, it may be necessary to add relevant device driver code to the project. We have already integrated a ROS version, so it might be worth considering utilizing ROS to handle online data acquisition.

If you want to first collect data and then read the dataset, you can refer to the parsing method of the EuRoC dataset and inherit the relevant classes to complete the dataset parsing.
