### ISSUE TITLE
cant find capture application source code

### ISSUE THREAD

**Issue by fingerx** [openxrlab/xrslam#5]
hi,thanks job but read http://doc.openxrlab.org.cn/openxrlab_document/ARDemo/ARdemo.html in "Data capturer on your phone" cant find capture application  source code . I'm not sure where I'm going wrong, I want to try compiling the capture program myself and learn. thanks

**Comment by itsuhane** [comment]
Data capture tool is only available on iOS and is provided as a testflight application. That means the source for the capture tool is not provided at this moment.
However, captured data are used by XRSfM and XRLocalization, the demo apps in XRSLAM should be self-sufficient and not requiring any data-capture by the user.

You should be able to run `xrslam-pc` on EuRoC or TUM datasets, or you can run `xrslam-ios` on recent iPhone models with realtime data from the phone.
The library code `xrslam` and `xrslam-extra` should built on Android without problem, but we haven't tested yet. Different from the iPhone lineage, there are just too many Android devices, some even have broken sensors. It's hard to add support (calibration) to all the devices so we skip Android app currently. Nevertheless the `xrslam` library exposes a very simple interface for visual-inertial tracking, you should be able to learn the usage from `xrslam-pc` and integrate it in your own app.
