### ISSUE TITLE
Compiler Problem

### ISSUE THREAD

**Issue by gongchenyear** [openxrlab/xrslam#52]
When I use clang 18.1.8 compile this project, it will encounter errors like following pictures.
![image](https://github.com/user-attachments/assets/0c18eed7-e3ee-474e-9e15-a850407bfbc4)
![image](https://github.com/user-attachments/assets/ac630580-1a72-486d-832c-57a16bf86112)
But when I use GNU 9.4.0 compile this project, it will not generate this problem, and it builds completely.
![image](https://github.com/user-attachments/assets/91b4b5d7-d436-454e-979d-a07e7fa56722)
![image](https://github.com/user-attachments/assets/c0c252a8-4af2-4ff7-8c0b-debb5663a1b7)
I wonder if this is a compiler issue or a bug in the code, and my ubuntu distro is 20.04, WSL2.

**Comment by panxkun** [comment]
you can try this issue #45
